<a href="https://colab.research.google.com/github/anushkagupta0203/Python-Libraries/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

In [29]:
np

<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>

In [60]:
a=[1,2,5]
m=np.array(a)
print(a)
print(type(a))
print(m)
print(type(m))
#Ndim Fun
print(m.ndim)
#n-dimension and direct printing
print(np.array(a,ndmin=2))
print(np.array(a,ndmin=3))

[1, 2, 5]
<class 'list'>
[1 2 5]
<class 'numpy.ndarray'>
[[1 2 5]]
1
[[[1 2 5]]]


In [58]:
#Arange function-(start,stop,step,dtype)
#last not included
#Dtype function
arr=np.arange(1,7,2)
print(arr)
print(arr.dtype)
arr=np.arange(1,7,2,dtype=float)
print(arr)
print(arr.dtype)

[1 3 5]
int64
[1. 3. 5.]
float64


In [61]:
#Multidimensional Array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[1,4,6]])
print(arr1)
#Ndim fun
print(arr1.ndim)
#Size fun
print(arr1.size)
print('Rows',np.size(arr1,0))
print('Column',np.size(arr1,1))
#Shape fun
print(arr1.shape)
# shape ~ size
print((np.size(arr1,0),np.size(arr1,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 6]]
2
12
Rows 4
Column 3
(4, 3)
(4, 3)


In [62]:
#Random Functions
#The numpy.random.rand() function creates an array of specified shape and fills it with random values.
np.random.rand(3,4)

array([[0.54668522, 0.19994994, 0.59183476, 0.9179166 ],
       [0.7792564 , 0.37506585, 0.43080139, 0.30715727],
       [0.07209957, 0.5026413 , 0.04837857, 0.91837482]])

In [64]:
#np.random.randint-used for random sampling in numpy- (low,high,size)
#random integers in range [low,high)
np.random.randint(1,10,5)

array([2, 2, 9, 1, 3])

In [66]:
#these fun can also be written as
np.random.randint(low=1,high=10,size=5)

array([8, 2, 8, 5, 7])

In [ ]:
#np.random.randn() fun fills with random values as per standard normal distribution


In [84]:
arr2=np.random.randint(1,10,(3,2))
print(arr2)
print(arr2.shape)
print( )
#Reshape fun
print(arr2.reshape(2,3))
print( )
print(arr2.reshape(6,1))

[[4 7]
 [9 6]
 [8 9]]
(3, 2)

[[4 7 9]
 [6 8 9]]

[[4]
 [7]
 [9]
 [6]
 [8]
 [9]]


In [89]:
#Linspace fun- (start,stop,NUMBER OF EQUIDISTANT VALUES REQUIRED,dtype(optional))
#remember e is not in the spelling
# diff in arange we have step instead
np.linspace(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [88]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [90]:
#flatten fun - multidimensional array-->single dimension
arr2.flatten()

array([4, 7, 9, 6, 8, 9])

In [91]:
#max,min,sum
print(arr2.max())
print(arr2.min())
print(arr2.sum())

9
4
43


In [100]:
#sort fun
print(arr2)
print()
print()
#colum-wise
print(np.sort(arr2, axis=0))
print()
print()
#row-wise
print(np.sort(arr2, axis=1))

[[4 7]
 [9 6]
 [8 9]]


[[4 6]
 [8 7]
 [9 9]]


[[4 7]
 [6 9]
 [8 9]]


In [107]:
#mathematical operations
print(arr2)
print()
print(arr2-1)
print()
print(arr2*2)
print()
#matrix multiplication- dot fun or @
print(arr1.dot(arr2))
print()
print(arr1@arr2)
print()
print(arr1**2)

[[4 7]
 [9 6]
 [8 9]]

[[3 6]
 [8 5]
 [7 8]]

[[ 8 14]
 [18 12]
 [16 18]]

[[ 46  46]
 [109 112]
 [172 178]
 [ 88  85]]

[[ 46  46]
 [109 112]
 [172 178]
 [ 88  85]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]
 [ 1 16 36]]


In [111]:
#mean,var,std
arr1=np.array([1,2,3,4,5])
print(arr1.mean())
print(arr1.var())
print(arr1.std())

3.0
2.0
1.4142135623730951


In [112]:
#filtering an numpy array
print(arr1<4)

[ True  True  True False False]


In [115]:
print(arr1[arr1<4])

[1 2 3]


In [124]:
#vsatck hstack concatenation
g=np.array([1,2,3])
h=np.array([4,5,6])
print(np.vstack((g,h)))
print()
print(np.hstack((g,h)))
print()
#splitting of array
i=np.vstack((g,h))
print(np.hsplit(i,3))
print(np.vsplit(i,2))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [3]:
l=[]
for i in range(0,11):
  m=[]
  for i in range(0,11):
    m.append(0)
  l.append(m)
print(l)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [24]:
l=np.zeros((10,10),dtype=int)
print(l)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [25]:
l1=np.ones((10,10),dtype=int)
print(l1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [27]:
l2=np.eye(10,dtype=int)
print(l2)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [71]:
#Empty Fun
#np.empty(shape=(3,3))